version: "3.7"
services:
  app:
    build:
      args:
        user: server-rsau
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: solo_rsau
    container_name: solo_rsau-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - solo_rsau_network

  nginx:
    image: nginx:alpine
    container_name: solo_rsau-nginx
    restart: unless-stopped
    ports:
      - 8083:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - solo_rsau_network

networks:
  solo_rsau_network:
    driver: bridge